---
name: Build basic container
on:
  push:
    tags:
      - '*'
env:
  DOCKER_NAME: "3sky/docker-dind"

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=my_tag::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: set tag
        uses: allenevans/set-env@v2.0.0
        with:
          TAG: ${{ steps.get_tag.outputs.my_tag }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f $(pwd)/Dockerfile -t $DOCKER_NAME:$TAG $(pwd)
      - name: Tag again
        run: docker tag $DOCKER_NAME:$TAG $DOCKER_NAME:latest
      - name: Push to registry
        run: docker push $DOCKER_NAME:$TAG && docker push $DOCKER_NAME:latest

  run-container:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Run the image
        run: docker run --privileged $DOCKER_NAME:latest trivy image --light $DOCKER_NAME:latest
