---
name: Deploy app to K8S pipeline
on:
  push:
    tags:
      - '*'
env:
  DOCKER_NAME: "docker-dind"

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f $(pwd)/Dockerfile -t $DOCKER_NAME:${{ steps.get_tag.outputs.TAG }} $(pwd)
